### ISSUE TITLE
Add a way to add items to the Holowardrobe directly via commands.

### ISSUE THREAD

**Issue by VeggieTheVegetable** [Dekker3D/NexusForever#19]
It would alleviate a lot of the bother of getting a full inventory and having to delete items for everyone playing the game.

**Comment by Zentoth** [comment]
Not sure that can be done, since the original game was not designed to work that way.
Did you give yourself maximum bagspace already?

**Comment by Dekker3D** [comment]
Fixed in 2e50cbcfe847f319cbe5bc55f23198c259f3ac83.
