### ISSUE TITLE
<!boost all> resetting

### ISSUE THREAD

**Issue by Zentoth** [Dekker3D/NexusForever#3]
After using < !boost all > and relogging, the level boost as well as the gained currencies reset to what they were before "boosting all". Combat abilities and Limited Action Set bar slot reset, too, resulting in available abilities displaying on locked slots if they were assigned after using the boost all command.
Holowardrobe Colors do remain, however.
Any gear bagged and equipped is not saved, either. The character logs back in with the level and gear they had before using <!boost all>.

**Comment by Dekker3D** [comment]
This works for some characters and not for others. Notably... the first character you make seems to fail?

**Comment by Zentoth** [comment]
<!boost all> as of 22-11-03
> keeps resetting on Char 01 of Acc 01
> worked for Char 02 on Acc 01 
   Note: char 02 has no active quests
> kept resetting upon logout for both Char 01 and Char 02 of Acc 02 :
   - checked with first starter zone quest not accepted and with first starter zone quest complete
   - checked after level boosting the second character to 20, 30, and 40 in various locations
   Note: Password was not changed during the first session and could not be changed later.
> worked for Char 01 of Acc 03 after changing the password, leaving the game and logging in with the new password
   Note: no quests were accepted
> worked for Char 02 of Acc 03
   Note: did nothing on first login, logged out, logged in, boosted, used [Switch Character]
 
 Can't create any additional characters, yet, because the entitlement command for additional character slots does not work.
 See separate issue.

**Comment by Zentoth** [comment]
<!boost all> as of 22-11-04

managed to have <!boost all> reset on Char 05 of Acc 01
- applied <!boost all> at the same quest status as when I tried it on Char 01 for the first time... I think

**Comment by Zentoth** [comment]
Fixed.
In addition <!boost all> also unlocks all lore.
