### ISSUE TITLE
!entitlement account commands don't work

### ISSUE THREAD

**Issue by Zentoth** [Dekker3D/NexusForever#9]
May just be a matter of permission to access.

alternate syntax /c entitlement account <ID> <n> does not work, either.

**Comment by Dekker3D** [comment]
This command has changed and requires documentation.

**Comment by Zentoth** [comment]
Entitlement commands updated in the documentation. New syntax:
/c entitlement add <EntitlementName> <amount>

**Comment by Dekker3D** [comment]
The most common entitlements are now granted by default, and you can add 1 of an entitlement by foregoing the "amount" parameter.
